# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylogcat < Formula
  desc "Interactive Android logcat viewer"
  homepage "https://github.com/parfenovvs/lazylogcat"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/parfenovvs/lazylogcat/releases/download/v0.7.0/lazylogcat_0.7.0_darwin_amd64.tar.gz"
      sha256 "3392b510b512729686e0f09b9fb3a0f254f845b1bdff767153a81b79c969b313"

      def install
        bin.install "lazylogcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/parfenovvs/lazylogcat/releases/download/v0.7.0/lazylogcat_0.7.0_darwin_arm64.tar.gz"
      sha256 "00fb48e289b4bf9bcbe003da4c062609844e993258e366b3de478aa146e7b0aa"

      def install
        bin.install "lazylogcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/parfenovvs/lazylogcat/releases/download/v0.7.0/lazylogcat_0.7.0_linux_amd64.tar.gz"
      sha256 "66530d746ee8ff2657bc95aaa97d034a1d89bf0a75c4c6372313461deee74f53"
      def install
        bin.install "lazylogcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/parfenovvs/lazylogcat/releases/download/v0.7.0/lazylogcat_0.7.0_linux_arm64.tar.gz"
      sha256 "694cdb6f8c33ad415caaf266fbd98db4b8a7fcf2f5c9aa65c44989c7e0c5de02"
      def install
        bin.install "lazylogcat"
      end
    end
  end

  test do
    system "#{bin}/lazylogcat", "version"
  end
end
